# Generated by Django 4.2.7 on 2024-01-08 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnchantedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('enchantment_level', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MagicalCreature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('magical_ability', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/magical_creatures')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Wizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('magical_abilities', models.TextField()),
                ('birth_date', models.DateField()),
                ('magical_wand', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/wizards')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MagicalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic_app.enchantedplace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MagicalEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.TextField()),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic_app.magicalcreature')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic_app.magicalevent')),
                ('wizard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magic_app.wizard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
